################################################################################
# Makefile for building and running docker containers

# PRODUCTION version -----------------------------------------------------------

production_build:
	docker pull mazamascience/airsensor:0.5.10
	docker tag mazamascience/airsensor:0.5.10 mazamascience/airsensor:latest
