################################################################################
# Makefile for building and running docker containers

# PRODUCTION version -----------------------------------------------------------

production_build:
	docker pull mazamascience/airsensor:0.8.2
	docker tag mazamascience/airsensor:0.8.2 mazamascience/airsensor:latest
